### ISSUE TITLE
Run Through #2 Feedback

### ISSUE THREAD

**Issue by glynnbird** [cloudant-labs/location-tracker-couchapp#3]
### Local test doesn't work

The tutorial says `You can test this out in your browser by opening the index.html file locally`. When I open file:///Users/glynnb/projects/locationtracker/_attachments/index.html in Chrome, I get dialog:

```
Error1 msg: User denied Geolocation
```

NOTE: tell users not to do file:///

In Firefox, it asks for permission to fetch the location, but I never get a lat/long back; I get a `permission denied` error several minutes later. (see 'Faulty cut-n-paste code' for the solution)
### Extraneous apostrophe

```
Cloudant has made this industry standard way of storing points, lines and polygons a cornerstone of it’s support
```

should read

```
Cloudant has made this industry standard way of storing points, lines and polygons a cornerstone of its support
```
## Faulty cut-n-paste code (again)

From Listing 3, change

```
document.getElementById('x').innerHTML = doc.geometry.coordinates[0];
document.getElementById('y').innerHTML = doc.geometry.coordinates[1];
document.getElementById('message').innerHTML =
        new Date(doc.properties.timestamp*1000);
```

 to

```
document.getElementById('x').innerHTML = position.coords.longitude;
document.getElementById('y').innerHTML = position.coords.latitude;
document.getElementById('message').innerHTML =
        new Date(position.timestamp);
```
## Use latest PouchDB

Swap 

```
<script src="http://cdn.jsdelivr.net/pouchdb/3.0.6/pouchdb.min.js"></script>
```

for

```
<script src="//cdn.jsdelivr.net/pouchdb/3.3.0/pouchdb.min.js"></script>
```
## Save button is disabled (again)

The save button code is 

```
<button id="saver" class="btn btn-danger" onclick="saveToServer()" disabled>Save</button>
```

But the button should not be disabled:

```
<button id="saver" class="btn btn-danger" onclick="saveToServer()">Save</button>
```
## Remind user to change map.html before deploying

The tutorial says `Now let’s deploy the mapping app. Take the code in Listing 7 and paste (or type) it into a file called map.html. Then redeploy the couchapp.`

But you need to edit the map.html to exchange `$USERNAME` for your Cloudant username, for this to work.
## Tracker app only works on HTTP, not HTTPS

If you visit http://reader.cloudant.com/locationtracker/_design/locationtracker/map.html it works! If you visit https://reader.cloudant.com/locationtracker/_design/locationtracker/map.html it doesn't. 

This is because Chrome is refusing to download insecure assets 
- Leaflet CSS
- PouchDB Javascript
- Bootstrap CSS

from a secure page.

**Comment by isc-rsingh** [comment]
All addressed in commit 0c8865f
